name: Cleanup

on:
  schedule:
    - cron: '0 1 * * *' # every day at 1am

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 days'    # delete artifacts older than this
          skip-tags: false # don't treat artifacts created by runs on tagged commits any differently
          skip-recent: 2   # keep the last 2 runs, regardless of age
